---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by noahi.
--- DateTime: 21/10/2023 01:33
---

ProfessionFramework.AlwaysUseStartingKits = false

local addProfession = ProfessionFramework.addProfession

addProfession('teacher', {
    name = "UI_prof_teacher",
    icon = "prof_teacher",
    cost = -6,
    xp = {
        [Perks.Woodwork] = 1,
        [Perks.Cooking] = 1,
        [Perks.Electricity] = 2,
        [Perks.MetalWelding] = 1,
        [Perks.Mechanics] = 1,
        [Perks.Tailoring] = 1,
        [Perks.Sprinting] = 4,
        [Perks.Maintenance] = 2,
        [Perks.Doctor] = 3,
    },
    traits = {"FastLearner"},
})

addProfession('seamstress', {
    name = "UI_prof_seamstress",
    icon = "prof_seamstress",
    cost = -6,
    xp = {
        [Perks.Tailoring] = 6,
        [Perks.SmallBlade] = 2,
        [Perks.Maintenance] = 2,
    },
    recipes = {"Make Cake Batter", "Make Pie Dough", "Make Bread Dough"},
    traits = {"ThickSkinned"},
    clothing = {
        Hat = {"Base.Hat_ChefHat"},
        TorsoExtra = {"Base.Apron_White", "Base.Apron_Black"},
        Shoes =  {"Base.Shoes_ArmyBoots", "Base.Shoes_ArmyBootsDesert", "Base.Shoes_BlackBoots"},
    },
})

addProfession('retired', {
    name = "UI_prof_retired",
    icon = "prof_retired",
    cost = -4,
    xp = {
        [Perks.Fitness] = -1,
        [Perks.Strength] = -1,
        [Perks.Cooking] = 5,
        [Perks.Doctor] = 3,
        [Perks.Farming] = 2,
        [Perks.Fishing] = 4,
        [Perks.PlantScavenging] = 3,
    },
    recipes = {"Make Cake Batter", "Make Pie Dough", "Make Bread Dough"},
    traits = {"ProneToIllness", "SlowHealer"},
    clothing = {
        FullTop = {"Base.Dungarees"},
    },
})

addProfession('musician', {
    name = "UI_prof_musician",
    icon = "prof_musician",
    cost = -6,
    xp = {
        [Perks.Electricity] = 2,
        [Perks.Music] = 7,
        [Perks.Nimble] = 3,
        [Perks.Dancing] = 6,
    },
    traits = {"Graceful"},
})

addProfession('bartender', {
    name = "UI_prof_bartender",
    icon = "prof_bartender",
    cost = -4,
    xp = {
        [Perks.Cooking] = 3,
        [Perks.Maintenance] = 4,
        [Perks.Nimble] = 3,
        [Perks.Doctor] = 2,
        [Perks.Aiming] = 2,
    },
})

